# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main_login:
            pattern: ^/login/$
            anonymous: true

        main:
            provider: main
            pattern: ^/
            anonymous: false

            form_login:
                login_path: login
                check_path: login_check
                default_target_path: smb_loyer_home

            logout:
                path:   logout
                target: login

    providers:
        main:
            entity: { class: SMBUserBundle:User, property: username }

    encoders:
        SMB\UserBundle\Entity\User: sha512

    role_hierarchy:
        # Un admin hérite des droits d'auteur et de modérateur
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_GESTIONNAIRE
        # On garde ce rôle superadmin, il nous resservira par la suite
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/gestion-loyer, roles: [ROLE_GESTIONNAIRE, ROLE_USER] }