<?php

namespace SMB\LoyerBundle\Entity;

use Doctrine\ORM\EntityRepository;
use SMB\LoyerBundle\Entity\Etudiant;
use SMB\LoyerBundle\Entity\Registre;
/**
 * CodificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodificationRepository extends EntityRepository
{
    /*******************************************************
     * fonction qui permet de recupérer la codification d'un
     * etudiant pour un registre donné
     *******************************************************/
    public function codification($etudiant,$registre){

            $qb=$this->createQuerybuilder('c');
            $qb->join('c.etudiant','e')
                    ->addSelect('e')
                    ->where('e.id =:etu')
                    ->setParameter('etu',$etudiant->getId())
                    ->join('c.registre','r')
                    ->addSelect('r')
                    ->andWhere('r.id =:reg')
                    ->setParameter('reg',$registre->getId());

            return $qb->getQuery()->getOneOrNullResult();
    }
}
