<?php

namespace SMB\LoyerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MoisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoisRepository extends EntityRepository
{
	/**************************************************************
	* méthode pour recupérer la liste des mois payé par l'étudiant 
	* passé en argument de la méthode
	***************************************************************/
	public function mois_paye($paiement){

		$qb=$this->createQuerybuilder('m');
		$qb->join('m.paiements','pa')
			->addSelect('pa')
			->where('pa.id =:id')
			->setParameter('id',$paiement->getId());
			
		return $qb->getQuery()->getResult();
	}
}
