<?php

namespace SMB\LoyerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PaiementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaiementRepository extends EntityRepository
{
	/**************************************************************
	* méthode pour recupérer la liste des paiement effectué pour 
	* la codification passée en argument de la méthode
	***************************************************************/
	public function paiements($codification){

		$qb=$this->createQuerybuilder('p');
		$qb->join('p.codification','codif')
			->addSelect('codif')
			->where('codif.id =:id')
			->setParameter('id',$codification->getId());
			
		return $qb->getQuery()->getResult();
	}
}
