<?php

namespace SMB\LoyerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PavionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PavionRepository extends EntityRepository
{
}
