<?php

namespace SMB\LoyerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegistreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistreRepository extends EntityRepository
{
	public function dernier_registre(){

		$qb=$this->createQueryBuilder('r');
		$qb->orderBy('r.id', 'DESC')
		->setMaxResults(1);

		return $qb->getQuery()
				->getOneOrNullResult();
	}
}
