etudiant:
    resource: "@SMBLoyerBundle/Resources/config/Routes/routing_etudiant.yml"

chambre:
    resource: "@SMBLoyerBundle/Resources/config/Routes/routing_chambre.yml"
    
pavion:
    resource: "@SMBLoyerBundle/Resources/config/Routes/routing_pavion.yml"
 
registre:
    resource: "@SMBLoyerBundle/Resources/config/Routes/routing_registre.yml"  
    
mois:
    resource: "@SMBLoyerBundle/Resources/config/Routes/routing_mois.yml"

loyer:
    resource: "@SMBLoyerBundle/Resources/config/Routes/routing_loyer.yml"
