<?php

namespace SMB\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function supprimer_utilisateur($id){

		$query=$this->_em->createQuery('DELETE FROM SMB\UserBundle\Entity\User u WHERE u.id='.$id);
		$result=$query->getResult();
	}	
}
