#****************************************
#Définition des routes pour Mois
#****************************************
smb_mois_home:
    path: /mois/index/
    defaults: { _controller: SMBLoyerBundle:Mois:index }

smb_mois_add:
    path: /mois/add/{id}/
    defaults: { _controller: SMBLoyerBundle:Mois:add }
    requirements:
        id: \d+
        
smb_mois_edit:
    path: /mois/edit/{id}/
    defaults: { _controller: SMBLoyerBundle:Mois:edit }
    requirements:
        id: \d+
 
smb_mois_delete:
    path: /mois/delete/{id}/
    defaults: { _controller: SMBLoyerBundle:Mois:delete }
    requirements:
        id: \d+
